//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM_PS28709.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class grade
    {
        public int ID { get; set; }
        public string MSSV { get; set; }
        public Nullable<double> TiengAnh { get; set; }
        public Nullable<double> TinHoc { get; set; }
        public Nullable<double> GDTD { get; set; }
    
        public virtual student student { get; set; }
    }
}
